language: cpp
sudo: required
dist: focal
compiler: gcc
os: linux
before install:
- sudo apt-get install cmake libgsl-dev
- pip install tox
script:
- mkdir build
- cd build
- cmake -DBUILD_TESTS=ON ..
- cmake --build .
- cd test
- ctest
- cd ../python
- tox
